# 01 — Dataset Preparation and Merging

This notebook prepares the datasets used in the dissertation. It imports five monthly macroeconomic series, standardises their column names and dates, defines the appropriate study periods, and exports the datasets required for the SARIMA and VAR analyses.

No modelling, forecasting or stationarity transformations are performed in this notebook.

**Import libraries**

`pandas` is used to load, transform and merge the datasets. `MonthEnd` is used to represent every monthly observation using the final calendar day of its corresponding month.

In [1]:
import pandas as pd
from pandas.tseries.offsets import MonthEnd

**Load the raw datasets**

The five monthly series are imported from CSV files downloaded from the BCRP statistical database. Latin-1 encoding is used because the original files contain Spanish characters, while the first row is skipped because it does not contain the required column headers.

In [2]:
inflation = pd.read_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/raw/inflation.csv", encoding='latin-1', skiprows=1)
interest = pd.read_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/raw/interest_rate.csv", encoding='latin-1', skiprows=1)
exchange = pd.read_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/raw/exchange_rate.csv", encoding='latin-1', skiprows=1)
gdp = pd.read_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/raw/gdp.csv", encoding='latin-1', skiprows=1)
liquidity = pd.read_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/raw/liquidity.csv", encoding='latin-1', skiprows=1)

**Inspect the imported datasets**

The first five observations of each dataset are displayed to confirm that the files were imported correctly and to inspect their original column names and structure.

In [3]:
inflation.head()

  Unnamed: 0  Índice de precios Lima Metropolitana (var% mensual) - IPC
0      Ene95                                           0.372189
1      Feb95                                           1.136291
2      Mar95                                           1.372020
3      Abr95                                           0.984568
4      May95                                           0.834709

In [4]:
interest.head()

,Unnamed: 0,Tasas de interés del Banco Central de Reserva - Tasa de Referencia de la Política Monetaria
0,Ene95,n.d.
1,Feb95,n.d.
2,Mar95,n.d.
3,Abr95,n.d.
4,May95,n.d.

In [5]:
exchange.head()

  Unnamed: 0  Índice del tipo de cambio real (base 2009=100) - Multilateral
0      Ene95                                          80.656505
1      Feb95                                          81.470118
2      Mar95                                          82.558884
3      Abr95                                          83.720810
4      May95                                          84.020555

In [6]:
gdp.head()

,Unnamed: 0,Producto bruto interno y demanda interna (índice 2007 = 100) - PBI
0,Ene95,60.5806961565215
1,Feb95,57.5549380176915
2,Mar95,59.3363859007712
3,Abr95,60.1380373824766
4,May95,66.9105360828403

In [7]:
liquidity.head()

,Unnamed: 0,Liquidez del sistema bancario (fin de periodo) - Liquidez en Soles (millones S/)
0,Ene95,6337.4791
1,Feb95,6593.6899
2,Mar95,6912.4266
3,Abr95,6991.7176
4,May95,7024.3098

**Standardise column names**

The original BCRP column names are replaced with shorter and consistent English names. Each dataset contains a monthly date column and one variable column.

In [8]:
inflation.columns = ["Date", "Inflation"]
interest.columns = ["Date", "Interest"]
exchange.columns = ["Date", "Exchange Rate"]
gdp.columns = ["Date", "GDP"]
liquidity.columns = ["Date", "Liquidity"]

**Standardise the monthly dates**

The original files use Spanish month abbreviations, so these are replaced with English abbreviations before converting the dates to datetime format. All dates are then set to the last day of the month to keep the monthly index consistent across the datasets.

In [9]:
month_map = {
    "Ene": "Jan",
    "Feb": "Feb",
    "Mar": "Mar",
    "Abr": "Apr",
    "May": "May",
    "Jun": "Jun",
    "Jul": "Jul",
    "Ago": "Aug",
    "Sep": "Sep",
    "Oct": "Oct",
    "Nov": "Nov",
    "Dic": "Dec"
}

In [10]:
inflation["Date"] = inflation["Date"].replace(month_map, regex=True)
inflation["Date"] = pd.to_datetime(inflation["Date"], format="%b%y")

In [11]:
interest["Date"] = interest["Date"].replace(month_map, regex=True)
interest["Date"] = pd.to_datetime(interest["Date"],format="%b%y")

In [12]:
exchange["Date"] = exchange["Date"].replace(month_map, regex=True)
exchange["Date"] = pd.to_datetime(exchange["Date"],format="%b%y")

In [13]:
gdp["Date"] = gdp["Date"].replace(month_map, regex=True)
gdp["Date"] = pd.to_datetime(gdp["Date"],format="%b%y")

In [14]:
liquidity["Date"] = liquidity["Date"].replace(month_map, regex=True)
liquidity["Date"] = pd.to_datetime(liquidity["Date"],format="%b%y")

In [15]:
inflation["Date"] = inflation["Date"] + MonthEnd(0)
interest["Date"] = interest["Date"] + MonthEnd(0)
exchange["Date"] = exchange["Date"] + MonthEnd(0)
gdp["Date"] = gdp["Date"] + MonthEnd(0)
liquidity["Date"] = liquidity["Date"] + MonthEnd(0)

**Verify the prepared series**

The structure and first observations of each dataset are displayed after date conversion. This confirms the number of observations, column names, date format and current data types before the datasets are exported or merged.

In [16]:
inflation.info()
inflation.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       372 non-null    datetime64[ns]
 1   Inflation  372 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 5.9 KB

        Date  Inflation
0 1995-01-31   0.372189
1 1995-02-28   1.136291
2 1995-03-31   1.372020
3 1995-04-30   0.984568
4 1995-05-31   0.834709

In [17]:
interest.info()
interest.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      372 non-null    datetime64[ns]
 1   Interest  372 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 5.9+ KB

        Date Interest
0 1995-01-31     n.d.
1 1995-02-28     n.d.
2 1995-03-31     n.d.
3 1995-04-30     n.d.
4 1995-05-31     n.d.

In [18]:
exchange.info()
exchange.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           378 non-null    datetime64[ns]
 1   Exchange Rate  378 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 6.0 KB

        Date  Exchange Rate
0 1995-01-31      80.656505
1 1995-02-28      81.470118
2 1995-03-31      82.558884
3 1995-04-30      83.720810
4 1995-05-31      84.020555

In [19]:
gdp.info()
gdp.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    378 non-null    datetime64[ns]
 1   GDP     378 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 6.0+ KB

        Date               GDP
0 1995-01-31  60.5806961565215
1 1995-02-28  57.5549380176915
2 1995-03-31  59.3363859007712
3 1995-04-30  60.1380373824766
4 1995-05-31  66.9105360828403

In [20]:
liquidity.info()
liquidity.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       372 non-null    datetime64[ns]
 1   Liquidity  372 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 5.9 KB

        Date  Liquidity
0 1995-01-31  6337.4791
1 1995-02-28  6593.6899
2 1995-03-31  6912.4266
3 1995-04-30  6991.7176
4 1995-05-31  7024.3098

**Export the full inflation series**

The complete inflation series, covering January 1995 to December 2025, is exported for the univariate SARIMA analysis. This export is completed before restricting the datasets to the shorter multivariate study period.

In [21]:
df_inflation = inflation.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_inflation_sarima.csv", index=False)

**Define the multivariate study period**

All five series are restricted to the common period from September 2003 to December 2025. September 2003 is used as the starting point because the BCRP policy interest rate was introduced at that time.

In [22]:
start_date = "2003-09-30"
end_date = "2025-12-31"

inflation = inflation[inflation["Date"].between(start_date, end_date)]
exchange = exchange[exchange["Date"].between(start_date, end_date)]
interest = interest[interest["Date"].between(start_date, end_date)]
gdp = gdp[gdp["Date"].between(start_date, end_date)]
liquidity = liquidity[liquidity["Date"].between(start_date, end_date)]

**Export the individual multivariate series**

The five datasets covering the common multivariate study period are exported separately. These files preserve the prepared individual series before they are combined.

In [23]:
inflation.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_inflation_multivar.csv", index=False)
exchange.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_exchange.csv", index=False)
interest.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_interest.csv", index=False)
gdp.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_gdp.csv", index=False)
liquidity.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/df_liquidity.csv", index=False)

**Merge the multivariate datasets**

The datasets are merged sequentially using the monthly date column. An inner join retains only dates that are present in every series, producing a complete common dataset for the multivariate analysis.

In [24]:
merged = inflation.merge(gdp, on="Date", how="inner")
merged = merged.merge(exchange, on="Date", how="inner")
merged = merged.merge(interest, on="Date", how="inner")
merged = merged.merge(liquidity, on="Date", how="inner")

The merged dataset is displayed to verify its variable order, date range and observations before export.

In [25]:
merged

,Date,Inflation,GDP,Exchange Rate,Interest,Liquidity
0,2003-09-30,0.558598,73.8678353680876,100.492827,2.75,18669.571905
1,2003-10-31,0.049032,77.5989135108107,101.854399,2.75,18795.623996
2,2003-11-30,0.167685,75.5725386288336,102.125159,2.5,19113.295522
3,2003-12-31,0.563951,78.0097324133558,102.395661,2.5,19812.133396
4,2004-01-31,0.537447,75.9132669251778,103.202148,2.5,20326.727396
...,...,...,...,...,...,...
263,2025-08-31,-0.290254,192.453607679855,90.320003,4.5,350189.568751
264,2025-09-30,0.011152,195.356042202986,89.833077,4.25,350518.552327
265,2025-10-31,-0.099627,196.694490026355,87.670632,4.25,353785.252444
266,2025-11-30,0.110782,193.04044192398,86.377724,4.25,364391.372020
267,2025-12-31,0.244109,213.891197196504,86.522129,4.25,383367.075281

**Export and verify the merged dataset**

The final multivariate dataset is exported as `merged.csv`. Its structure, missing values, duplicated dates and dimensions are then inspected to confirm that it is ready for subsequent analysis.

In [26]:
merged.to_csv("/content/drive/MyDrive/MSc_Dissertation/datasets/processed/merged.csv", index=False)

In [27]:
merged.info()

merged.isna().sum()

merged.duplicated(subset="Date").sum()

merged.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           268 non-null    datetime64[ns]
 1   Inflation      268 non-null    float64
 2   GDP            268 non-null    object
 3   Exchange Rate  268 non-null    float64
 4   Interest       268 non-null    object
 5   Liquidity      268 non-null    float64
dtypes: datetime64[ns](1), float64(3), object(2)
memory usage: 12.7+ KB

(268, 6)